### PR TITLE
Enable Gradle Enterprise

### LINKED ISSUE #4335: enable Gradle enterprise
Enabling Gradle Enterprise unlocks a few things for the project:

1. More metrics and faster build times in general
2. Shared network cache enabling maintainers and contributors to complete a build within seconds

### PR DESCRIPTION
**Pull request by Goooler**
Closes #4335

### CODE REVIEW

**Comment by BoD** [comment]
Thanks! 

Just a heads up that we are exploring if we'll be able to obtain a [non free](https://gradle.com/pricing/) license of Gradle Enterprise.

**Comment by Goooler** [comment]
ok

**Comment by Goooler** [comment]
@martinbonnin Can we enable build scan publishing for now? I believe it might be useful for us.

**Comment by martinbonnin** [comment]
@Goooler I think so, let me circle back internally to double check we're OK with the terms & conditions but it should be possible 👍

**Pull request closed without merging**
