### PR TITLE
[Doc] Add apollo-kotlin-java-support to Galaxy page

### PR DESCRIPTION
**Pull request by BoD**

### CODE REVIEW

**Review by martinbonnin — APPROVED** [review]
Good catch 👍

**Comment by martinbonnin** [comment]
nodejs is looking down again:
```
8:00:14 PM: Downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz...
8:02:36 PM: curl: (18) transfer closed with 12357444 bytes remaining to read
8:02:36 PM: Binary download from https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz failed, trying source.
8:02:36 PM: grep: /opt/buildhome/.nvm/.cache/bin/node-v16.20.2-linux-x64/node-v16.20.2-linux-x64.tar.xz: No such file or directory
```

**Comment by BoD** [comment]
Seems to be up again. Can seem to restart the checks though... Ok if I merge anyway?

**Comment by martinbonnin** [comment]
> Seems to be up again. Can seem to restart the checks though... Ok if I merge anyway?

Sure 👍

**Pull request merged**
