### PR TITLE
Kotlin 1.6.10

### PR DESCRIPTION
**Pull request by kubode**
To fix https://github.com/apollographql/apollo-kotlin/issues/3722.

### CODE REVIEW

**Comment by kubode** [comment]
I've checked on my local.

1. Publish Apollo to my local.

    ```sh
    # apollo-kotlin
    ./gradlew publishToMavenLocal
    ```

1. Modify Apollo version to `3.0.0-rc04-SNAPSHOT` on our KMM project.
1. Publish our KMM project to my local.

    ```sh
    ./gradlew publishToMavenLocal
    ```

There are no errors!

**Comment by martinbonnin** [comment]
Good catch, thanks!

**Comment by BoD** [comment]
The build failed because of an incorrect import, unrelated to this PR! See #3726

**Comment by BoD** [comment]
(I've rebased this branch on main)

**Comment by kubode** [comment]
Thanks!

**Review by martinbonnin — APPROVED** [review]

**Pull request merged**
