### PR TITLE
Fix file name discrepancies and bring attention to server null data no errors issue in Kotlin Tutorial

### PR DESCRIPTION
**Pull request by YuanRuQian**
Hi, I mentioned these issues in [my Discord post](https://discord.com/channels/1022972389463687228/1219320092530184264)

Changes Made:

- Fixed a typo in the ["Add More Info" section](https://www.apollographql.com/docs/kotlin/tutorial/06-add-more-info/) where it incorrectly mentioned "LaunchListAdapter.kt" instead of "LaunchList.kt" for binding GraphQL data.
- Addressed a mention in the ["Subscriptions" section](https://www.apollographql.com/docs/kotlin/tutorial/11-subscriptions/#handle-errors) regarding error handling location in the client code. The mentioned location (MainActivity.kt) didn't match the actual code (Apollo.kt).

Additionally, In the ["Add a Details View" section ](https://www.apollographql.com/docs/kotlin/tutorial/08-add-a-details-view), I observed a discrepancy in the behavior of the [current server demo](https://studio.apollographql.com/sandbox/explorer) when handling invalid IDs. According to the [expected behavior](https://www.apollographql.com/docs/kotlin/tutorial/08-add-a-details-view#handle-application-errors), the server should return errors when provided with invalid IDs. However, upon testing by providing invalid IDs in the query, all responses contained only null data but no errors. Maybe the dev team to investigate this issue to ensure new learners encounter the expected behavior. 

Query:
```graphql
query LaunchDetails($id: ID!) {
  launch(id: $id) {
    id
    site
    mission {
      name
      missionPatch(size: LARGE)
    }
    rocket {
      name
      type
    }
    isBooked
  }
}
```

Query Variables:
```json
{
  "id": "invalidId"
}
```

Expected response:
```json
{
  "errors": [
    {
      "message": "Cannot read property 'flight_number' of undefined",
      "locations": [
        {
          "line": 1,
          "column": 32
        }
      ],
      "path": [
        "launch"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": {
    "launch": null
  }
}
```

Actual response:
Screenshot 2024-03-18 at 3 17 37 PM

Thank you!

### CODE REVIEW

**Review by martinbonnin — APPROVED** [review]
Thanks a lot for catching those ❤️ 

You're also 100% right on the behaviour change about errors vs null. [Nullability in GraphQL](https://github.com/graphql/nullability-wg/) is one of my favorite topics, I'll investigate this with the team and report here

**Review by BoD — APPROVED** [review]
👍

**Comment by martinbonnin** [comment]
(keeping this open for now as a reminder that we still need to investigate the tutorial issue). 

I'll merge and open a separate tutorial issue at the end of the week if we haven't figured it out before that!

**Comment by martinbonnin** [comment]
Fixing the tutorial might take a bit of time. Merging this as-is as opened https://github.com/apollographql/apollo-kotlin/issues/5747 as a follow up. Thanks again 🙏

**Pull request merged**
