### PR TITLE
Draft: Fix fan out in websocket network transport

### PR DESCRIPTION
**Pull request by baconz**
What about something like this as a fix for https://github.com/apollographql/apollo-kotlin/issues/4805 ?

### CODE REVIEW

**Comment by martinbonnin** [comment]
Thanks for looking into this. Would be nice to have some integration tests on this. I'll see what I can do.

**Comment by martinbonnin** [comment]
I just added an integration test. It's all timing based so I hope it will not create too many flakes but on the other hand, since this is all implementation details, I don't really see another way to to it. Let me now what you think.

**Review by BoD — APPROVED** [review]
This looks good! Thanks!

**Comment by martinbonnin** [comment]
Merging this cause I want to include it in an upcoming maintainance release. Let me know if you have any concerns @baconz

**Review by martinbonnin — APPROVED** [review]

**Comment by baconz** [comment]
@martinbonnin sorry I was late to the party on this one.

Merging sounds good, and I think a bunch of folks here will be happy to get their hands on this!

I think the test could be improved by having `reopenWhen` emit to a flow that triggers the server to start again after at least 2 attempts. We could assert that the flow sees only one emission in the face of a server outage.

I tried to get that working, but TBH couldn't figure out how to get the server running on my machine.

**Comment by martinbonnin** [comment]
> couldn't figure out how to get the server running on my machine

The server starts automatically from the integration test. If you open the `apollo-kotlin/tests` folder in IntelliJ, you should even be able to click the small green triangle to run it.

**Pull request merged**
