### PR TITLE
Configuration Cache: mark KotlinJsIrLink and KotlinNative link as not compatible with CC and disable CC

### PR DESCRIPTION
**Pull request by martinbonnin**

### CODE REVIEW

**Review by BoD — APPROVED** [review]
👍

**Review by BoD — APPROVED** [review]

**Comment by martinbonnin** [comment]
I've ended up disabling CC altogether here 🤷

**Comment by BoD** [comment]
> I've ended up disabling CC altogether here 🤷

Yeah we can try again in the future. 👍

(there's also one in `build-logic/gradle.properties`, did you keep it intentionally?)

**Review by BoD — APPROVED** [review]

**Comment by martinbonnin** [comment]
> there's also one in build-logic/gradle.properties, did you keep it intentionally?

Complete oversight, thanks!

**Pull request merged**
