### PR TITLE
Override JsonNumber.toString()

### PR DESCRIPTION
**Pull request by jvanderwee**
Related to https://github.com/apollographql/apollo-kotlin-adapters/issues/28

### CODE REVIEW

**Review by martinbonnin — APPROVED** [review]
Thanks!

**Comment by jvanderwee** [comment]
@martinbonnin just checking I've done the right thing with the .api file? how is this meant to be updated?

**Comment by martinbonnin** [comment]
That's perfect, thanks! I wasn't expecting this to be part of the ABI since all objects have a `toString()` but I guess it is technically part of it. I'll merge once everything is green ✅

**Comment by martinbonnin** [comment]
Turns out the native klib ABI dumps also needed to be updated. Not sure why they weren't. Maybe you forgot to add a file to your commit? In all cases, I have added them in https://github.com/apollographql/apollo-kotlin/pull/6273/commits/ba9465394e3f99ebbbd05df904452d056717640c

**Comment by martinbonnin** [comment]
Thanks!

**Pull request merged**
