### PR TITLE
Enable dokka again 🎉 

### PR DESCRIPTION
**Pull request by martinbonnin**
- Revert "disable Kdoc on 4.x (#4705)"
- bump dokka

See https://github.com/Kotlin/dokka/releases/tag/v1.8.10

### CODE REVIEW

**Review by BoD — APPROVED** [review]
👍

**Comment by martinbonnin** [comment]
[CI failed](https://github.com/apollographql/apollo-kotlin/actions/runs/4343373305/jobs/7585336358) with an IntelliJ error: 

```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':intellij-plugin:patchPluginXml'.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:715)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$600(DefaultTaskContainer.java:76)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.domainObjectCreationException(DefaultTaskContainer.java:707)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:948)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.access$1401(DefaultTaskContainer.java:654)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:680)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.tryCreate(DefaultTaskContainer.java:676)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.calculateOwnValue(DefaultNamedDomainObjectCollection.java:929)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:108)
	at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:100)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:334)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:329)
	at org.gradle.api.internal.collections.DefaultPendingSource.realize(DefaultPendingSource.java:62)
	at org.gradle.api.internal.collections.DefaultPendingSource.realizePending(DefaultPendingSource.java:52)
	at org.gradle.api.internal.collections.SortedSetElementSource.realizePending(SortedSetElementSource.java:112)
	at org.gradle.api.internal.collections.FilteredCollection.iterator(FilteredCollection.java:160)
	at org.gradle.api.internal.collections.FilteredCollection.size(FilteredCollection.java:173)
	at org.gradle.api.internal.DefaultDomainObjectCollection.size(DefaultDomainObjectCollection.java:426)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.Iterables.toArray(Iterables.java:295)
	at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:135)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:103)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
	... 141 more
Caused by: java.lang.NoSuchMethodError: 'void org.intellij.markdown.parser.MarkdownParser.<init>(org.intellij.markdown.flavours.MarkdownFlavourDescriptor)'
	at org.jetbrains.changelog.ExtensionsKt.markdownToHTML(extensions.kt:13)
```

@BoD can you check if there's a DGP <-> IGP incompatibility somewhere?

**Comment by BoD** [comment]
> can you check if there's a DGP <-> IGP incompatibility somewhere?

Updated the changelog plugin to its latest version, looks like it fixes the issue

**Comment by martinbonnin** [comment]
> Updated the changelog plugin to its latest version, looks like it fixes the issue

39e6272b53aa361f93ca7b4432a8e775_t

**Pull request merged**
